language: node_js
node_js: node
cache:
directories:
- node_modules
script:
- npm test
env:
- CI=true
deploy:
provider: script
script: npm install netlify-cli -g && npm run build && netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
skip_cleanup: true
on:
branch: master
